FROM oakestra/vm-ubuntu:25.04

# install docker
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get --yes install --no-install-recommends \
        linux-image-extra-virtual \
        docker.io \
        nginx \
        libnginx-mod-http-perl

# create 'wolf' user
RUN useradd -m -s /usr/bin/bash -G video,render,input,docker wolf \
    && echo 'wolf:wolf' | chpasswd

# Load uhid module on boot
COPY <<EOF /etc/modules-load.d/uhid.conf
uhid
EOF

# Install udev rules for wolf
COPY <<EOF /etc/udev/rules.d/85-wolf-virtual-inputs.rules
# Allows Wolf to access /dev/uinput
KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="input", OPTIONS+="static_node=uinput"

# Allows Wolf to access /dev/uhid
KERNEL=="uhid", TAG+="uaccess"

# Move virtual keyboard and mouse into a different seat
SUBSYSTEMS=="input", ATTRS{id/vendor}=="ab00", MODE="0660", GROUP="input", ENV{ID_SEAT}="seat9"

# Joypads
SUBSYSTEMS=="input", ATTRS{name}=="Wolf X-Box One (virtual) pad", MODE="0660", GROUP="input"
SUBSYSTEMS=="input", ATTRS{name}=="Wolf PS5 (virtual) pad", MODE="0660", GROUP="input"
SUBSYSTEMS=="input", ATTRS{name}=="Wolf gamepad (virtual) motion sensors", MODE="0660", GROUP="input"
SUBSYSTEMS=="input", ATTRS{name}=="Wolf Nintendo (virtual) pad", MODE="0660", GROUP="input"
EOF

# Systemd units for wolf and nginx
COPY --chown=root:root --chmod=0644 wolf.service /etc/systemd/system/wolf.service
COPY --chown=root:root --chmod=0644 nginx.service.override /etc/systemd/system/nginx.service.d/override.conf
COPY --chown=root:root --chmod=0644 nginx.conf.template /etc/nginx/nginx.conf.template

RUN systemctl enable wolf.service

RUN useradd -m ubuntu -G sudo -s /usr/bin/bash \
    && echo 'ubuntu:ubuntu' | chpasswd \
