# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import monitoringNotification_pb2 as proto_dot_monitoringNotification__pb2


class MonitoringServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyDeployment = channel.unary_unary(
                '/monitoring.MonitoringService/NotifyDeployment',
                request_serializer=proto_dot_monitoringNotification__pb2.MonitoringRequest.SerializeToString,
                response_deserializer=proto_dot_monitoringNotification__pb2.MonitoringResponse.FromString,
                )


class MonitoringServiceServicer(object):
    """Service definition
    """

    def NotifyDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyDeployment,
                    request_deserializer=proto_dot_monitoringNotification__pb2.MonitoringRequest.FromString,
                    response_serializer=proto_dot_monitoringNotification__pb2.MonitoringResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitoring.MonitoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonitoringService(object):
    """Service definition
    """

    @staticmethod
    def NotifyDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/monitoring.MonitoringService/NotifyDeployment',
            proto_dot_monitoringNotification__pb2.MonitoringRequest.SerializeToString,
            proto_dot_monitoringNotification__pb2.MonitoringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
