# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/monitoringNotification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"proto/monitoringNotification.proto\x12\nmonitoring\"|\n\x11MonitoringRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\x10\n\x08job_hash\x18\x02 \x01(\t\x12\x17\n\x0finstance_number\x18\x03 \x01(\x05\x12*\n\x08resource\x18\x04 \x01(\x0b\x32\x18.monitoring.ResourceInfo\"p\n\x0cResourceInfo\x12\x0b\n\x03\x63pu\x18\x01 \x01(\t\x12\x0e\n\x06memory\x18\x02 \x01(\t\x12\x0b\n\x03gpu\x18\x03 \x01(\t\x12\x0c\n\x04\x64isk\x18\x04 \x01(\t\x12(\n\x07network\x18\x05 \x01(\x0b\x32\x17.monitoring.NetworkInfo\":\n\x0bNetworkInfo\x12\x14\n\x0c\x62\x61ndwidth_in\x18\x01 \x01(\t\x12\x15\n\rbandwidth_out\x18\x02 \x01(\t\";\n\x12MonitoringResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2h\n\x11MonitoringService\x12S\n\x10NotifyDeployment\x12\x1d.monitoring.MonitoringRequest\x1a\x1e.monitoring.MonitoringResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.monitoringNotification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MONITORINGREQUEST']._serialized_start=50
  _globals['_MONITORINGREQUEST']._serialized_end=174
  _globals['_RESOURCEINFO']._serialized_start=176
  _globals['_RESOURCEINFO']._serialized_end=288
  _globals['_NETWORKINFO']._serialized_start=290
  _globals['_NETWORKINFO']._serialized_end=348
  _globals['_MONITORINGRESPONSE']._serialized_start=350
  _globals['_MONITORINGRESPONSE']._serialized_end=409
  _globals['_MONITORINGSERVICE']._serialized_start=411
  _globals['_MONITORINGSERVICE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
