// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: requests/proto/migration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the service ID and payload.
type MigrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MigrationToken string                 `protobuf:"bytes,2,opt,name=migration_token,json=migrationToken,proto3" json:"migration_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrationRequest) Reset() {
	*x = MigrationRequest{}
	mi := &file_requests_proto_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRequest) ProtoMessage() {}

func (x *MigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRequest.ProtoReflect.Descriptor instead.
func (*MigrationRequest) Descriptor() ([]byte, []int) {
	return file_requests_proto_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *MigrationRequest) GetMigrationToken() string {
	if x != nil {
		return x.MigrationToken
	}
	return ""
}

// Send the actual service migration data.
type MigrationData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MigrationToken string                 `protobuf:"bytes,2,opt,name=migration_token,json=migrationToken,proto3" json:"migration_token,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrationData) Reset() {
	*x = MigrationData{}
	mi := &file_requests_proto_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationData) ProtoMessage() {}

func (x *MigrationData) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationData.ProtoReflect.Descriptor instead.
func (*MigrationData) Descriptor() ([]byte, []int) {
	return file_requests_proto_migration_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationData) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *MigrationData) GetMigrationToken() string {
	if x != nil {
		return x.MigrationToken
	}
	return ""
}

func (x *MigrationData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// The response message indicating success and a message.
type MigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationResponse) Reset() {
	*x = MigrationResponse{}
	mi := &file_requests_proto_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationResponse) ProtoMessage() {}

func (x *MigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationResponse.ProtoReflect.Descriptor instead.
func (*MigrationResponse) Descriptor() ([]byte, []int) {
	return file_requests_proto_migration_proto_rawDescGZIP(), []int{2}
}

func (x *MigrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_requests_proto_migration_proto protoreflect.FileDescriptor

const file_requests_proto_migration_proto_rawDesc = "" +
	"\n" +
	"\x1erequests/proto/migration.proto\x12\trequesrts\"Z\n" +
	"\x10MigrationRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12'\n" +
	"\x0fmigration_token\x18\x02 \x01(\tR\x0emigrationToken\"q\n" +
	"\rMigrationData\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12'\n" +
	"\x0fmigration_token\x18\x02 \x01(\tR\x0emigrationToken\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"G\n" +
	"\x11MigrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfa\x01\n" +
	"\x10MigrationService\x12J\n" +
	"\x10ReceiveMigration\x12\x18.requesrts.MigrationData\x1a\x1c.requesrts.MigrationResponse\x12M\n" +
	"\x10RequestMigration\x12\x1b.requesrts.MigrationRequest\x1a\x1c.requesrts.MigrationResponse\x12K\n" +
	"\x0eMigrationAbort\x12\x1b.requesrts.MigrationRequest\x1a\x1c.requesrts.MigrationResponseB\x10Z\x0erequests/protob\x06proto3"

var (
	file_requests_proto_migration_proto_rawDescOnce sync.Once
	file_requests_proto_migration_proto_rawDescData []byte
)

func file_requests_proto_migration_proto_rawDescGZIP() []byte {
	file_requests_proto_migration_proto_rawDescOnce.Do(func() {
		file_requests_proto_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_requests_proto_migration_proto_rawDesc), len(file_requests_proto_migration_proto_rawDesc)))
	})
	return file_requests_proto_migration_proto_rawDescData
}

var file_requests_proto_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_requests_proto_migration_proto_goTypes = []any{
	(*MigrationRequest)(nil),  // 0: requesrts.MigrationRequest
	(*MigrationData)(nil),     // 1: requesrts.MigrationData
	(*MigrationResponse)(nil), // 2: requesrts.MigrationResponse
}
var file_requests_proto_migration_proto_depIdxs = []int32{
	1, // 0: requesrts.MigrationService.ReceiveMigration:input_type -> requesrts.MigrationData
	0, // 1: requesrts.MigrationService.RequestMigration:input_type -> requesrts.MigrationRequest
	0, // 2: requesrts.MigrationService.MigrationAbort:input_type -> requesrts.MigrationRequest
	2, // 3: requesrts.MigrationService.ReceiveMigration:output_type -> requesrts.MigrationResponse
	2, // 4: requesrts.MigrationService.RequestMigration:output_type -> requesrts.MigrationResponse
	2, // 5: requesrts.MigrationService.MigrationAbort:output_type -> requesrts.MigrationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_requests_proto_migration_proto_init() }
func file_requests_proto_migration_proto_init() {
	if File_requests_proto_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_requests_proto_migration_proto_rawDesc), len(file_requests_proto_migration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_requests_proto_migration_proto_goTypes,
		DependencyIndexes: file_requests_proto_migration_proto_depIdxs,
		MessageInfos:      file_requests_proto_migration_proto_msgTypes,
	}.Build()
	File_requests_proto_migration_proto = out.File
	file_requests_proto_migration_proto_goTypes = nil
	file_requests_proto_migration_proto_depIdxs = nil
}
