// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: requests/proto/migration.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MigrationService_ReceiveMigration_FullMethodName = "/requesrts.MigrationService/ReceiveMigration"
	MigrationService_RequestMigration_FullMethodName = "/requesrts.MigrationService/RequestMigration"
	MigrationService_MigrationAbort_FullMethodName   = "/requesrts.MigrationService/MigrationAbort"
)

// MigrationServiceClient is the client API for MigrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The migration service definition.
type MigrationServiceClient interface {
	ReceiveMigration(ctx context.Context, in *MigrationData, opts ...grpc.CallOption) (*MigrationResponse, error)
	RequestMigration(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error)
	MigrationAbort(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error)
}

type migrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrationServiceClient(cc grpc.ClientConnInterface) MigrationServiceClient {
	return &migrationServiceClient{cc}
}

func (c *migrationServiceClient) ReceiveMigration(ctx context.Context, in *MigrationData, opts ...grpc.CallOption) (*MigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_ReceiveMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) RequestMigration(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_RequestMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrationServiceClient) MigrationAbort(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*MigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationResponse)
	err := c.cc.Invoke(ctx, MigrationService_MigrationAbort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigrationServiceServer is the server API for MigrationService service.
// All implementations must embed UnimplementedMigrationServiceServer
// for forward compatibility.
//
// The migration service definition.
type MigrationServiceServer interface {
	ReceiveMigration(context.Context, *MigrationData) (*MigrationResponse, error)
	RequestMigration(context.Context, *MigrationRequest) (*MigrationResponse, error)
	MigrationAbort(context.Context, *MigrationRequest) (*MigrationResponse, error)
	mustEmbedUnimplementedMigrationServiceServer()
}

// UnimplementedMigrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigrationServiceServer struct{}

func (UnimplementedMigrationServiceServer) ReceiveMigration(context.Context, *MigrationData) (*MigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMigration not implemented")
}
func (UnimplementedMigrationServiceServer) RequestMigration(context.Context, *MigrationRequest) (*MigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMigration not implemented")
}
func (UnimplementedMigrationServiceServer) MigrationAbort(context.Context, *MigrationRequest) (*MigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrationAbort not implemented")
}
func (UnimplementedMigrationServiceServer) mustEmbedUnimplementedMigrationServiceServer() {}
func (UnimplementedMigrationServiceServer) testEmbeddedByValue()                          {}

// UnsafeMigrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrationServiceServer will
// result in compilation errors.
type UnsafeMigrationServiceServer interface {
	mustEmbedUnimplementedMigrationServiceServer()
}

func RegisterMigrationServiceServer(s grpc.ServiceRegistrar, srv MigrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedMigrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MigrationService_ServiceDesc, srv)
}

func _MigrationService_ReceiveMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).ReceiveMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_ReceiveMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).ReceiveMigration(ctx, req.(*MigrationData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_RequestMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).RequestMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_RequestMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).RequestMigration(ctx, req.(*MigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrationService_MigrationAbort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrationServiceServer).MigrationAbort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrationService_MigrationAbort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrationServiceServer).MigrationAbort(ctx, req.(*MigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MigrationService_ServiceDesc is the grpc.ServiceDesc for MigrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MigrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "requesrts.MigrationService",
	HandlerType: (*MigrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMigration",
			Handler:    _MigrationService_ReceiveMigration_Handler,
		},
		{
			MethodName: "RequestMigration",
			Handler:    _MigrationService_RequestMigration_Handler,
		},
		{
			MethodName: "MigrationAbort",
			Handler:    _MigrationService_MigrationAbort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "requests/proto/migration.proto",
}
