user root
persistence true
persistence_location /mosquitto/data/
log_dest stdout

listener 8883
allow_anonymous false

cafile /certs/ca.crt
certfile /certs/cluster.crt
keyfile /certs/cluster.key
require_certificate true
use_identity_as_username true
tls_version tlsv1.2
