version: "3"
services:

  # MQTT 
  mqtt:
    image: eclipse-mosquitto:2.0
    hostname: mqtt
    container_name: mqtt
    networks:
      - cluster_net
    expose:
      - "10003"
    ports:
      - "10003:10003"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
    healthcheck:
      test: [ "CMD-SHELL", "timeout -t 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 6
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      
  # cluster-level mongoDB
  mongo_cluster:
    image: mongo:3.6
    container_name: cluster_mongo
    hostname: cluster_mongo
    networks:
      - cluster_net
    ports:
      - "10107:10107"
    volumes:
      - 'mongodb_cluster_data:/mongodb'
    command: mongod --port 10107 --ipv6
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

# cluster-level mongoDB
  mongo_clusternet:
    image: mongo:3.6
    container_name: cluster_mongo_net
    hostname: cluster_mongo_net
    networks:
      - cluster_net
    ports:
      - "10108:10108"
    volumes:
      - 'mongodb_cluster_net_data:/mongodb'
    command: mongod --port 10108 --ipv6
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

# Cluster Manager
  cluster_service_manager:
    image: ghcr.io/oakestra/oakestra-net/cluster-service-manager:v0.04.amd64.experimental
    container_name: cluster_service_manager
    hostname: cluster_service_manager
    networks:
      - cluster_net
    expose:
      - "10110"
    ports:
      - "10110:10110"
    environment:
      - MY_PORT=10110
      - MQTT_BROKER_PORT=10003
      - MQTT_BROKER_URL=mqtt
      - ROOT_SERVICE_MANAGER_URL=192.168.178.22
      - ROOT_SERVICE_MANAGER_PORT=10099
      - SYSTEM_MANAGER_URL=cluster_manager
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=cluster_mongo_net
      - CLUSTER_MONGO_PORT=10108
    depends_on:
      - mongo_clusternet
      - mqtt
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

# Cluster Manager
  cluster_manager:
    image: cluster_manager
    build: cluster-manager/
    container_name: cluster_manager
    hostname: cluster_manager
    expose:
      - "10100"
      - "10101"
    networks:
      - cluster_net
    ports:
      - "10100:10100"
      - "10101:10101"
    environment:
      - MY_PORT=10100
      - SYSTEM_MANAGER_URL=192.168.178.22
      - SYSTEM_MANAGER_URL_v6=[2001:a61:123a:8701:8fd1:fe65:eb97:6870]
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_SERVICE_MANAGER_ADDR=cluster_service_manager
      - CLUSTER_SERVICE_MANAGER_PORT=10110
      - CLUSTER_MONGO_URL=cluster_mongo
      - CLUSTER_MONGO_PORT=10107
      - CLUSTER_SCHEDULER_URL=cluster_scheduler
      - CLUSTER_SCHEDULER_PORT=10105
      - MQTT_BROKER_URL=mqtt
      - MQTT_BROKER_PORT=10003
      - CLUSTER_NAME=Walhalla
      - CLUSTER_LOCATION=PARIS
    depends_on:
      - mongo_cluster
      - mqtt
      - cluster_scheduler
      - cluster_service_manager
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  # Cluster Scheduler
  cluster_scheduler:
    image: cluster_scheduler
    build: cluster-scheduler/
    container_name: cluster_scheduler
    hostname: cluster_scheduler
    networks:
      - cluster_net
    expose:
      - "10105"
    ports:
      - "10105:10105"
    environment:
      - MY_PORT=10105
      - CLUSTER_MANAGER_URL=cluster_manager
      - CLUSTER_MANAGER_PORT=10100
      - CLUSTER_MONGO_URL=cluster_mongo
      - CLUSTER_MONGO_PORT=10107
      - REDIS_ADDR=redis://:clusterRedis@cluster_redis:6479
    depends_on:
      - cluster_redis
      - mongo_cluster
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  # Redis for the Cluster Scheduler as Job Queue
  cluster_redis:
    image: redis
    hostname: cluster_redis
    container_name: cluster_redis
    networks:
      - cluster_net
    ports:
      - "6479:6479"
    command: redis-server --requirepass clusterRedis --port 6479
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    networks:
      - cluster_net
    ports:
      - 10009:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - cluster_manager
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

volumes:
  mongodb_cluster_data:
    driver: local
  mongodb_cluster_net_data:
    driver: local

networks:
  cluster_net:
    name: cluster_net
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:b::/64
          gateway: 2001:db8:b::1
        - subnet: 192.168.129.0/24
          gateway: 192.168.129.1
