x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    
services:
  addons_manager:
    image: addons_manager
    container_name: addons_manager
    build: ../addons_engine/addons-manager/
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    environment:
      - ADDONS_MANAGER_PORT=${ADDONS_MANAGER_PORT}
      - ADDONS_ENGINE_MONGO_URL=mongo
      - ADDONS_ENGINE_MONGO_PORT=${CLOUD_MONGO_PORT}
      - MARKETPLACE_ADDR=http://marketplace_manager:${ADDONS_MARKETPLACE_PORT}
    ports:
      - ${ADDONS_MANAGER_PORT}:${ADDONS_MANAGER_PORT}
    depends_on:
      - mongo_root
      - marketplace_manager
    logging: *default-logging

  addons_monitor:
    image: addons_monitor
    container_name: addons_monitor
    build: ../addons_engine/addons-monitor/
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADDONS_MANAGER_ADDR=http://addons_manager:${ADDONS_MANAGER_PORT}
    depends_on:
      - addons_manager
    logging: *default-logging

  marketplace_manager:
    image: marketplace_manager
    build: ../addons_marketplace/marketplace-manager/
    container_name: marketplace_manager
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - ${ADDONS_MARKETPLACE_PORT}
    ports:
      - ${ADDONS_MARKETPLACE_PORT}:${ADDONS_MARKETPLACE_PORT}
    environment:
      - ADDON_MARKETPLACE_PORT=${ADDONS_MARKETPLACE_PORT}
      - ADDON_MARKETPLACE_MONGO_URL=mongo
      - ADDON_MARKETPLACE_MONGO_PORT=${CLOUD_MONGO_PORT}
    depends_on:
      - mongo_root
    logging: *default-logging

