{
 "title": "[Oakestra] Root Orchestrator - Infrastructure Dashboard",
 "description": "Oakestra Orchestration Framework for Edge Computing. Root Orchestrator Monitoring Logs Infrastructure Dashboard. More info at https://oakestra.io/",
 "tags": [
  "Loki",
  "logging",
  "oakestra-root-infra"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "service",
    "label": "service",
    "query": {}
   },
   {
    "name": "infrastructure",
    "label": "Infrastructure Level Logs",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "General Logs stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregated Log Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$service\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Log Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=~\"$service\"} |~ `(?i)$searchable_pattern` |= `Errno` [$__interval]))"
    },
    {
     "expr": "sum(count_over_time({container_name=~\"$service\"} |~ `(?i)$searchable_pattern` |= `err` [$__interval]))"
    },
    {
     "expr": "sum(count_over_time({container_name=~\"$service\"} |~ `(?i)$searchable_pattern` |= `KeyError` [$__interval]))"
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(logstream) (count_over_time({job=~\"$infrastructure\"} [$__interval]))",
     "legendFormat": "{{label.Name}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$service\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container_name=~\"$service\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "format": "short",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container_name) (count_over_time({job=~\"$infrastructure\"} |~ `(?i)$searchable_pattern` | container_name=~\"$service\" [$__interval]))",
     "legendFormat": "{{label.Name}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$service\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (logstream)",
     "legendFormat": "{{label.Name}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({container_name=~\"$service\"} |~ \"(?i)$searchable_pattern\")[30s])) by (logstream)",
     "legendFormat": "{{label.Name}}"
    }
   ]
  },
  { "title": "Alarming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  { "title": "Loki Rules - Active alarms", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 } },
  { "title": "Root Level Services Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "System Manager Logs: filtered by \"$searchable_pattern\"",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\", container_name=\"system_manager\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  },
  {
   "title": "Root Service Manager Logs: filtered by \"$searchable_pattern\"",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\", container_name=\"root_service_manager\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  },
  {
   "title": "Resource Abstractor Logs: filtered by \"$searchable_pattern\"",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\", container_name=\"resource_abstractor\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  },
  {
   "title": "Root Scheduler Logs: filtered by \"$searchable_pattern\"",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\", container_name=\"root_scheduler\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  }
 ]
}