// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HookEvent.
const (
	PostCreate HookEvent = "post_create"
	PostDelete HookEvent = "post_delete"
	PostUpdate HookEvent = "post_update"
	PreCreate  HookEvent = "pre_create"
	PreDelete  HookEvent = "pre_delete"
	PreUpdate  HookEvent = "pre_update"
)

// Valid indicates whether the value is a known member of the HookEvent enum.
func (e HookEvent) Valid() bool {
	switch e {
	case PostCreate:
		return true
	case PostDelete:
		return true
	case PostUpdate:
		return true
	case PreCreate:
		return true
	case PreDelete:
		return true
	case PreUpdate:
		return true
	default:
		return false
	}
}

// Application Application metadata. Unknown fields are stored and returned verbatim.
type Application struct {
	ID *ObjectID `json:"_id,omitempty"`

	// ApplicationID Set server-side on creation to the document's own `_id`.
	ApplicationID        *string                `json:"applicationID,omitempty"`
	ApplicationDesc      *string                `json:"application_desc,omitempty"`
	ApplicationName      *string                `json:"application_name,omitempty"`
	ApplicationNamespace *string                `json:"application_namespace,omitempty"`
	Microservices        *[]string              `json:"microservices,omitempty"`
	UserId               *string                `json:"userId,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// CustomResourceDefinition A dynamically registered resource type.
type CustomResourceDefinition struct {
	ID *ObjectID `json:"_id,omitempty"`

	// ResourceType Names the type and the path segment its instances live under
	// (`/api/v1/custom-resources/{resource_type}`).
	ResourceType string `json:"resource_type"`

	// Schema JSON Schema every instance of this type is validated against. An
	// absent or empty schema imposes no constraint.
	Schema *map[string]interface{} `json:"schema,omitempty"`
}

// CustomResourceInstance One instance of a registered custom resource type. Its fields are
// whatever the type's own JSON Schema allows, so nothing beyond `_id` is
// fixed here.
type CustomResourceInstance struct {
	ID                   *ObjectID              `json:"_id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeletedID defines model for DeletedID.
type DeletedID struct {
	ID string `json:"_id"`
}

// HistorySample defines model for HistorySample.
type HistorySample struct {
	Timestamp *float64 `json:"timestamp,omitempty"`
	Value     *float64 `json:"value,omitempty"`
}

// Hook A webhook registration.
type Hook struct {
	ID *ObjectID `json:"_id,omitempty"`

	// Entity The entity to fire for: `resources`, `applications`, `jobs`, or a
	// registered custom `resource_type`.
	Entity     *string      `json:"entity,omitempty"`
	Events     *[]HookEvent `json:"events,omitempty"`
	HookName   *string      `json:"hook_name,omitempty"`
	WebhookUrl *string      `json:"webhook_url,omitempty"`
}

// HookEvent `pre_*` events fire synchronously before the write and may return a
// transformed payload that is persisted in place of the original.
// `post_*` events fire asynchronously after the write, receiving only the
// affected document's id.
type HookEvent string

// Job A deployed microservice and its per-worker instances. Jobs carry the
// whole SLA the user submitted, so unknown fields are the norm here -
// they are stored and returned verbatim.
type Job struct {
	ID            *ObjectID `json:"_id,omitempty"`
	ApplicationID *string   `json:"applicationID,omitempty"`

	// Candidate Id of the candidate resource this job is placed on.
	Candidate    *string        `json:"candidate,omitempty"`
	InstanceList *[]JobInstance `json:"instance_list,omitempty"`

	// JobName Unique per deployment; the key `PUT /api/v1/jobs` upserts on.
	JobName              *string                `json:"job_name,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// JobHistorySample A job instance's cpu/memory history sample. Unlike Resource's
// HistorySample, timestamp is an ISO-8601 string
// (datetime.now(timezone.utc).isoformat()), not a Unix-seconds number -
// the two aren't interchangeable.
type JobHistorySample struct {
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Value     *float64   `json:"value,omitempty"`
}

// JobInstance One running copy of a job on one worker.
type JobInstance struct {
	CpuHistory     *[]JobHistorySample `json:"cpu_history,omitempty"`
	CpuPercent     *float64            `json:"cpu_percent,omitempty"`
	Disk           *float64            `json:"disk,omitempty"`
	HostIp         *string             `json:"host_ip,omitempty"`
	HostPort       *int                `json:"host_port,omitempty"`
	InstanceNumber *int                `json:"instance_number,omitempty"`

	// LastModifiedTimestamp Unix seconds. Unlike cpu_history/memory_history's timestamp
	// (server-generated on every PATCH), this one is taken from the
	// request body verbatim - the caller (cluster_manager) sets it
	// before sending.
	LastModifiedTimestamp *float64               `json:"last_modified_timestamp,omitempty"`
	Logs                  *string                `json:"logs,omitempty"`
	MemoryHistory         *[]JobHistorySample    `json:"memory_history,omitempty"`
	MemoryPercent         *float64               `json:"memory_percent,omitempty"`
	Publicip              *string                `json:"publicip,omitempty"`
	Status                *string                `json:"status,omitempty"`
	StatusDetail          *string                `json:"status_detail,omitempty"`
	WorkerId              *string                `json:"worker_id,omitempty"`
	AdditionalProperties  map[string]interface{} `json:"-"`
}

// JobInstanceAppend Body of `PUT /api/v1/jobs/{job_id}/{instance_id}`. Only the last
// element of `instance_list` is appended; earlier elements are ignored.
type JobInstanceAppend struct {
	InstanceList *[]JobInstance `json:"instance_list,omitempty"`
}

// Message A bare status or error message.
//
// Example: {"message":"Not Found"}
type Message struct {
	Message string `json:"message"`
}

// ObjectID Example: 65f1c0d2a1b2c3d4e5f60718
type ObjectID = string

// Resource A candidate resource: a worker node at cluster level, a whole cluster
// at root level. Unknown fields are stored and returned verbatim.
type Resource struct {
	ID *ObjectID `json:"_id,omitempty"`

	// Active True when `last_modified_timestamp` falls within the last 30
	// seconds. Computed per request rather than persisted, and outside
	// the canonical projection - so it is only present on
	// `GET /api/v1/resources` and only when asked for explicitly, with
	// `?resources=active`.
	Active                     *bool                   `json:"active,omitempty"`
	ActiveNodes                *int                    `json:"active_nodes,omitempty"`
	AggregationPerArchitecture *map[string]interface{} `json:"aggregation_per_architecture,omitempty"`
	Architecture               *string                 `json:"architecture,omitempty"`
	CandidateLocation          *string                 `json:"candidate_location,omitempty"`
	CandidateName              *string                 `json:"candidate_name,omitempty"`

	// CpuHistory Most recent 100 cpu samples, appended server-side.
	CpuHistory *[]HistorySample `json:"cpu_history,omitempty"`
	CpuPercent *float64         `json:"cpu_percent,omitempty"`
	CsiDrivers *[]interface{}   `json:"csi_drivers,omitempty"`
	GpuPercent *int             `json:"gpu_percent,omitempty"`
	Ip         *string          `json:"ip,omitempty"`

	// LastModifiedTimestamp Unix seconds, refreshed server-side on every usage report.
	LastModifiedTimestamp *float64 `json:"last_modified_timestamp,omitempty"`
	Memory                *int     `json:"memory,omitempty"`

	// MemoryHistory Most recent 100 memory samples, appended server-side.
	MemoryHistory        *[]HistorySample       `json:"memory_history,omitempty"`
	MemoryPercent        *float64               `json:"memory_percent,omitempty"`
	Port                 *string                `json:"port,omitempty"`
	SupportedAddons      *[]string              `json:"supported_addons,omitempty"`
	Vcpus                *int                   `json:"vcpus,omitempty"`
	Vgpus                *int                   `json:"vgpus,omitempty"`
	Virtualization       *[]string              `json:"virtualization,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ValidationError A validation failure, carrying per-field messages under `details`. The
// shape of `details` follows the failing location: `{"body": {...}}` for
// request bodies and `{"query": {...}}` for query parameters.
//
// Example: {"details":{"query":{"active":["active must be a valid boolean"]}},"message":"Invalid input"}
type ValidationError struct {
	Details map[string]interface{} `json:"details"`

	// Message Example: Invalid input
	Message string `json:"message"`
}

// ApplicationName defines model for ApplicationName.
type ApplicationName = string

// ApplicationNamespace defines model for ApplicationNamespace.
type ApplicationNamespace = string

// ApplicationUserID defines model for ApplicationUserID.
type ApplicationUserID = string

// CustomResourceType defines model for CustomResourceType.
type CustomResourceType = string

// InstanceID defines model for InstanceID.
type InstanceID = int

// JobApplicationID defines model for JobApplicationID.
type JobApplicationID = string

// JobID Example: 65f1c0d2a1b2c3d4e5f60718
type JobID = ObjectID

// JobInstanceNumber defines model for JobInstanceNumber.
type JobInstanceNumber = string

// JobName defines model for JobName.
type JobName = string

// ResourceActive defines model for ResourceActive.
type ResourceActive = string

// ResourceCandidateName defines model for ResourceCandidateName.
type ResourceCandidateName = string

// ResourceIP defines model for ResourceIP.
type ResourceIP = string

// ResourceJobID Example: 65f1c0d2a1b2c3d4e5f60718
type ResourceJobID = ObjectID

// ResourceProjection defines model for ResourceProjection.
type ResourceProjection = []string

// BadRequest A bare status or error message.
//
// Example: {"message":"Not Found"}
type BadRequest = Message

// InvalidInput A validation failure, carrying per-field messages under `details`. The
// shape of `details` follows the failing location: `{"body": {...}}` for
// request bodies and `{"query": {...}}` for query parameters.
//
// Example: {"details":{"query":{"active":["active must be a valid boolean"]}},"message":"Invalid input"}
type InvalidInput = ValidationError

// NotFound A bare status or error message.
//
// Example: {"message":"Not Found"}
type NotFound = Message

// ResourceList defines model for ResourceList.
type ResourceList = []Resource

// ListApplicationsParams defines parameters for ListApplications.
type ListApplicationsParams struct {
	ApplicationName      *ApplicationName      `form:"application_name,omitempty" json:"application_name,omitempty"`
	ApplicationNamespace *ApplicationNamespace `form:"application_namespace,omitempty" json:"application_namespace,omitempty"`
	UserId               *ApplicationUserID    `form:"userId,omitempty" json:"userId,omitempty"`
}

// GetApplicationParams defines parameters for GetApplication.
type GetApplicationParams struct {
	ApplicationName      *ApplicationName      `form:"application_name,omitempty" json:"application_name,omitempty"`
	ApplicationNamespace *ApplicationNamespace `form:"application_namespace,omitempty" json:"application_namespace,omitempty"`
	UserId               *ApplicationUserID    `form:"userId,omitempty" json:"userId,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	ApplicationID *JobApplicationID `form:"applicationID,omitempty" json:"applicationID,omitempty"`
	JobName       *JobName          `form:"job_name,omitempty" json:"job_name,omitempty"`
}

// GetJobParams defines parameters for GetJob.
type GetJobParams struct {
	// InstanceNumber Narrow the result to jobs carrying an instance with this number.
	//
	// Typed as a numeric string rather than an integer so that a
	// non-numeric value keeps returning the 422 `Invalid input` body the
	// original Flask service returned, rather than a plain 400.
	InstanceNumber *JobInstanceNumber `form:"instance_number,omitempty" json:"instance_number,omitempty"`
}

// ListResourcesParams defines parameters for ListResources.
type ListResourcesParams struct {
	// Active When truthy, only return candidates that reported within the freshness
	// window (30 seconds).
	//
	// Typed as a string rather than a boolean because the original Flask
	// service parsed it with marshmallow, which accepts `1`, `t`, `true`,
	// `on`, `y`, `yes` and their false counterparts (`0`, `f`, `false`,
	// `off`, `n`, `no`), case-insensitively. Anything else is a 422.
	Active *ResourceActive `form:"active,omitempty" json:"active,omitempty"`

	// JobId Return only the candidate the given job is placed on. Resolved through
	// the job's `candidate` field, so an unknown job or one not yet placed
	// is a 404.
	JobId         *ResourceJobID         `form:"job_id,omitempty" json:"job_id,omitempty"`
	CandidateName *ResourceCandidateName `form:"candidate_name,omitempty" json:"candidate_name,omitempty"`
	Ip            *ResourceIP            `form:"ip,omitempty" json:"ip,omitempty"`

	// Resources Extra document fields to include beyond the canonical projection, as a
	// comma-separated list.
	Resources *ResourceProjection `form:"resources,omitempty" json:"resources,omitempty"`
}

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = Application

// PatchApplicationJSONRequestBody defines body for PatchApplication for application/json ContentType.
type PatchApplicationJSONRequestBody = Application

// CreateCustomResourceDefinitionJSONRequestBody defines body for CreateCustomResourceDefinition for application/json ContentType.
type CreateCustomResourceDefinitionJSONRequestBody = CustomResourceDefinition

// CreateCustomResourceInstanceJSONRequestBody defines body for CreateCustomResourceInstance for application/json ContentType.
type CreateCustomResourceInstanceJSONRequestBody = CustomResourceInstance

// PatchCustomResourceInstanceJSONRequestBody defines body for PatchCustomResourceInstance for application/json ContentType.
type PatchCustomResourceInstanceJSONRequestBody = CustomResourceInstance

// CreateHookJSONRequestBody defines body for CreateHook for application/json ContentType.
type CreateHookJSONRequestBody = Hook

// PatchHookJSONRequestBody defines body for PatchHook for application/json ContentType.
type PatchHookJSONRequestBody = Hook

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = Job

// UpsertJobJSONRequestBody defines body for UpsertJob for application/json ContentType.
type UpsertJobJSONRequestBody = Job

// PatchJobJSONRequestBody defines body for PatchJob for application/json ContentType.
type PatchJobJSONRequestBody = Job

// PatchJobInstanceJSONRequestBody defines body for PatchJobInstance for application/json ContentType.
type PatchJobInstanceJSONRequestBody = JobInstance

// AppendJobInstanceJSONRequestBody defines body for AppendJobInstance for application/json ContentType.
type AppendJobInstanceJSONRequestBody = JobInstanceAppend

// CreateResourceJSONRequestBody defines body for CreateResource for application/json ContentType.
type CreateResourceJSONRequestBody = Resource

// UpsertResourceJSONRequestBody defines body for UpsertResource for application/json ContentType.
type UpsertResourceJSONRequestBody = Resource

// PatchResourceJSONRequestBody defines body for PatchResource for application/json ContentType.
type PatchResourceJSONRequestBody = Resource

// Getter for additional properties for Application. Returns the specified
// element and whether it was found
func (a Application) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Application
func (a *Application) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Application to handle AdditionalProperties
func (a *Application) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["_id"]; found {
		err = json.Unmarshal(raw, &a.ID)
		if err != nil {
			return fmt.Errorf("error reading '_id': %w", err)
		}
		delete(object, "_id")
	}

	if raw, found := object["applicationID"]; found {
		err = json.Unmarshal(raw, &a.ApplicationID)
		if err != nil {
			return fmt.Errorf("error reading 'applicationID': %w", err)
		}
		delete(object, "applicationID")
	}

	if raw, found := object["application_desc"]; found {
		err = json.Unmarshal(raw, &a.ApplicationDesc)
		if err != nil {
			return fmt.Errorf("error reading 'application_desc': %w", err)
		}
		delete(object, "application_desc")
	}

	if raw, found := object["application_name"]; found {
		err = json.Unmarshal(raw, &a.ApplicationName)
		if err != nil {
			return fmt.Errorf("error reading 'application_name': %w", err)
		}
		delete(object, "application_name")
	}

	if raw, found := object["application_namespace"]; found {
		err = json.Unmarshal(raw, &a.ApplicationNamespace)
		if err != nil {
			return fmt.Errorf("error reading 'application_namespace': %w", err)
		}
		delete(object, "application_namespace")
	}

	if raw, found := object["microservices"]; found {
		err = json.Unmarshal(raw, &a.Microservices)
		if err != nil {
			return fmt.Errorf("error reading 'microservices': %w", err)
		}
		delete(object, "microservices")
	}

	if raw, found := object["userId"]; found {
		err = json.Unmarshal(raw, &a.UserId)
		if err != nil {
			return fmt.Errorf("error reading 'userId': %w", err)
		}
		delete(object, "userId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Application to handle AdditionalProperties
func (a Application) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ID != nil {
		object["_id"], err = json.Marshal(a.ID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '_id': %w", err)
		}
	}

	if a.ApplicationID != nil {
		object["applicationID"], err = json.Marshal(a.ApplicationID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'applicationID': %w", err)
		}
	}

	if a.ApplicationDesc != nil {
		object["application_desc"], err = json.Marshal(a.ApplicationDesc)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'application_desc': %w", err)
		}
	}

	if a.ApplicationName != nil {
		object["application_name"], err = json.Marshal(a.ApplicationName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'application_name': %w", err)
		}
	}

	if a.ApplicationNamespace != nil {
		object["application_namespace"], err = json.Marshal(a.ApplicationNamespace)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'application_namespace': %w", err)
		}
	}

	if a.Microservices != nil {
		object["microservices"], err = json.Marshal(a.Microservices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'microservices': %w", err)
		}
	}

	if a.UserId != nil {
		object["userId"], err = json.Marshal(a.UserId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'userId': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CustomResourceInstance. Returns the specified
// element and whether it was found
func (a CustomResourceInstance) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CustomResourceInstance
func (a *CustomResourceInstance) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CustomResourceInstance to handle AdditionalProperties
func (a *CustomResourceInstance) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["_id"]; found {
		err = json.Unmarshal(raw, &a.ID)
		if err != nil {
			return fmt.Errorf("error reading '_id': %w", err)
		}
		delete(object, "_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CustomResourceInstance to handle AdditionalProperties
func (a CustomResourceInstance) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ID != nil {
		object["_id"], err = json.Marshal(a.ID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '_id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Job. Returns the specified
// element and whether it was found
func (a Job) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Job
func (a *Job) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Job to handle AdditionalProperties
func (a *Job) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["_id"]; found {
		err = json.Unmarshal(raw, &a.ID)
		if err != nil {
			return fmt.Errorf("error reading '_id': %w", err)
		}
		delete(object, "_id")
	}

	if raw, found := object["applicationID"]; found {
		err = json.Unmarshal(raw, &a.ApplicationID)
		if err != nil {
			return fmt.Errorf("error reading 'applicationID': %w", err)
		}
		delete(object, "applicationID")
	}

	if raw, found := object["candidate"]; found {
		err = json.Unmarshal(raw, &a.Candidate)
		if err != nil {
			return fmt.Errorf("error reading 'candidate': %w", err)
		}
		delete(object, "candidate")
	}

	if raw, found := object["instance_list"]; found {
		err = json.Unmarshal(raw, &a.InstanceList)
		if err != nil {
			return fmt.Errorf("error reading 'instance_list': %w", err)
		}
		delete(object, "instance_list")
	}

	if raw, found := object["job_name"]; found {
		err = json.Unmarshal(raw, &a.JobName)
		if err != nil {
			return fmt.Errorf("error reading 'job_name': %w", err)
		}
		delete(object, "job_name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Job to handle AdditionalProperties
func (a Job) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ID != nil {
		object["_id"], err = json.Marshal(a.ID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '_id': %w", err)
		}
	}

	if a.ApplicationID != nil {
		object["applicationID"], err = json.Marshal(a.ApplicationID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'applicationID': %w", err)
		}
	}

	if a.Candidate != nil {
		object["candidate"], err = json.Marshal(a.Candidate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'candidate': %w", err)
		}
	}

	if a.InstanceList != nil {
		object["instance_list"], err = json.Marshal(a.InstanceList)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance_list': %w", err)
		}
	}

	if a.JobName != nil {
		object["job_name"], err = json.Marshal(a.JobName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'job_name': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for JobInstance. Returns the specified
// element and whether it was found
func (a JobInstance) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for JobInstance
func (a *JobInstance) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for JobInstance to handle AdditionalProperties
func (a *JobInstance) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cpu_history"]; found {
		err = json.Unmarshal(raw, &a.CpuHistory)
		if err != nil {
			return fmt.Errorf("error reading 'cpu_history': %w", err)
		}
		delete(object, "cpu_history")
	}

	if raw, found := object["cpu_percent"]; found {
		err = json.Unmarshal(raw, &a.CpuPercent)
		if err != nil {
			return fmt.Errorf("error reading 'cpu_percent': %w", err)
		}
		delete(object, "cpu_percent")
	}

	if raw, found := object["disk"]; found {
		err = json.Unmarshal(raw, &a.Disk)
		if err != nil {
			return fmt.Errorf("error reading 'disk': %w", err)
		}
		delete(object, "disk")
	}

	if raw, found := object["host_ip"]; found {
		err = json.Unmarshal(raw, &a.HostIp)
		if err != nil {
			return fmt.Errorf("error reading 'host_ip': %w", err)
		}
		delete(object, "host_ip")
	}

	if raw, found := object["host_port"]; found {
		err = json.Unmarshal(raw, &a.HostPort)
		if err != nil {
			return fmt.Errorf("error reading 'host_port': %w", err)
		}
		delete(object, "host_port")
	}

	if raw, found := object["instance_number"]; found {
		err = json.Unmarshal(raw, &a.InstanceNumber)
		if err != nil {
			return fmt.Errorf("error reading 'instance_number': %w", err)
		}
		delete(object, "instance_number")
	}

	if raw, found := object["last_modified_timestamp"]; found {
		err = json.Unmarshal(raw, &a.LastModifiedTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'last_modified_timestamp': %w", err)
		}
		delete(object, "last_modified_timestamp")
	}

	if raw, found := object["logs"]; found {
		err = json.Unmarshal(raw, &a.Logs)
		if err != nil {
			return fmt.Errorf("error reading 'logs': %w", err)
		}
		delete(object, "logs")
	}

	if raw, found := object["memory_history"]; found {
		err = json.Unmarshal(raw, &a.MemoryHistory)
		if err != nil {
			return fmt.Errorf("error reading 'memory_history': %w", err)
		}
		delete(object, "memory_history")
	}

	if raw, found := object["memory_percent"]; found {
		err = json.Unmarshal(raw, &a.MemoryPercent)
		if err != nil {
			return fmt.Errorf("error reading 'memory_percent': %w", err)
		}
		delete(object, "memory_percent")
	}

	if raw, found := object["publicip"]; found {
		err = json.Unmarshal(raw, &a.Publicip)
		if err != nil {
			return fmt.Errorf("error reading 'publicip': %w", err)
		}
		delete(object, "publicip")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_detail"]; found {
		err = json.Unmarshal(raw, &a.StatusDetail)
		if err != nil {
			return fmt.Errorf("error reading 'status_detail': %w", err)
		}
		delete(object, "status_detail")
	}

	if raw, found := object["worker_id"]; found {
		err = json.Unmarshal(raw, &a.WorkerId)
		if err != nil {
			return fmt.Errorf("error reading 'worker_id': %w", err)
		}
		delete(object, "worker_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for JobInstance to handle AdditionalProperties
func (a JobInstance) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CpuHistory != nil {
		object["cpu_history"], err = json.Marshal(a.CpuHistory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cpu_history': %w", err)
		}
	}

	if a.CpuPercent != nil {
		object["cpu_percent"], err = json.Marshal(a.CpuPercent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cpu_percent': %w", err)
		}
	}

	if a.Disk != nil {
		object["disk"], err = json.Marshal(a.Disk)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'disk': %w", err)
		}
	}

	if a.HostIp != nil {
		object["host_ip"], err = json.Marshal(a.HostIp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'host_ip': %w", err)
		}
	}

	if a.HostPort != nil {
		object["host_port"], err = json.Marshal(a.HostPort)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'host_port': %w", err)
		}
	}

	if a.InstanceNumber != nil {
		object["instance_number"], err = json.Marshal(a.InstanceNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance_number': %w", err)
		}
	}

	if a.LastModifiedTimestamp != nil {
		object["last_modified_timestamp"], err = json.Marshal(a.LastModifiedTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_modified_timestamp': %w", err)
		}
	}

	if a.Logs != nil {
		object["logs"], err = json.Marshal(a.Logs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'logs': %w", err)
		}
	}

	if a.MemoryHistory != nil {
		object["memory_history"], err = json.Marshal(a.MemoryHistory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory_history': %w", err)
		}
	}

	if a.MemoryPercent != nil {
		object["memory_percent"], err = json.Marshal(a.MemoryPercent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory_percent': %w", err)
		}
	}

	if a.Publicip != nil {
		object["publicip"], err = json.Marshal(a.Publicip)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'publicip': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusDetail != nil {
		object["status_detail"], err = json.Marshal(a.StatusDetail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_detail': %w", err)
		}
	}

	if a.WorkerId != nil {
		object["worker_id"], err = json.Marshal(a.WorkerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'worker_id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Resource. Returns the specified
// element and whether it was found
func (a Resource) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Resource
func (a *Resource) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Resource to handle AdditionalProperties
func (a *Resource) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["_id"]; found {
		err = json.Unmarshal(raw, &a.ID)
		if err != nil {
			return fmt.Errorf("error reading '_id': %w", err)
		}
		delete(object, "_id")
	}

	if raw, found := object["active"]; found {
		err = json.Unmarshal(raw, &a.Active)
		if err != nil {
			return fmt.Errorf("error reading 'active': %w", err)
		}
		delete(object, "active")
	}

	if raw, found := object["active_nodes"]; found {
		err = json.Unmarshal(raw, &a.ActiveNodes)
		if err != nil {
			return fmt.Errorf("error reading 'active_nodes': %w", err)
		}
		delete(object, "active_nodes")
	}

	if raw, found := object["aggregation_per_architecture"]; found {
		err = json.Unmarshal(raw, &a.AggregationPerArchitecture)
		if err != nil {
			return fmt.Errorf("error reading 'aggregation_per_architecture': %w", err)
		}
		delete(object, "aggregation_per_architecture")
	}

	if raw, found := object["architecture"]; found {
		err = json.Unmarshal(raw, &a.Architecture)
		if err != nil {
			return fmt.Errorf("error reading 'architecture': %w", err)
		}
		delete(object, "architecture")
	}

	if raw, found := object["candidate_location"]; found {
		err = json.Unmarshal(raw, &a.CandidateLocation)
		if err != nil {
			return fmt.Errorf("error reading 'candidate_location': %w", err)
		}
		delete(object, "candidate_location")
	}

	if raw, found := object["candidate_name"]; found {
		err = json.Unmarshal(raw, &a.CandidateName)
		if err != nil {
			return fmt.Errorf("error reading 'candidate_name': %w", err)
		}
		delete(object, "candidate_name")
	}

	if raw, found := object["cpu_history"]; found {
		err = json.Unmarshal(raw, &a.CpuHistory)
		if err != nil {
			return fmt.Errorf("error reading 'cpu_history': %w", err)
		}
		delete(object, "cpu_history")
	}

	if raw, found := object["cpu_percent"]; found {
		err = json.Unmarshal(raw, &a.CpuPercent)
		if err != nil {
			return fmt.Errorf("error reading 'cpu_percent': %w", err)
		}
		delete(object, "cpu_percent")
	}

	if raw, found := object["csi_drivers"]; found {
		err = json.Unmarshal(raw, &a.CsiDrivers)
		if err != nil {
			return fmt.Errorf("error reading 'csi_drivers': %w", err)
		}
		delete(object, "csi_drivers")
	}

	if raw, found := object["gpu_percent"]; found {
		err = json.Unmarshal(raw, &a.GpuPercent)
		if err != nil {
			return fmt.Errorf("error reading 'gpu_percent': %w", err)
		}
		delete(object, "gpu_percent")
	}

	if raw, found := object["ip"]; found {
		err = json.Unmarshal(raw, &a.Ip)
		if err != nil {
			return fmt.Errorf("error reading 'ip': %w", err)
		}
		delete(object, "ip")
	}

	if raw, found := object["last_modified_timestamp"]; found {
		err = json.Unmarshal(raw, &a.LastModifiedTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'last_modified_timestamp': %w", err)
		}
		delete(object, "last_modified_timestamp")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["memory_history"]; found {
		err = json.Unmarshal(raw, &a.MemoryHistory)
		if err != nil {
			return fmt.Errorf("error reading 'memory_history': %w", err)
		}
		delete(object, "memory_history")
	}

	if raw, found := object["memory_percent"]; found {
		err = json.Unmarshal(raw, &a.MemoryPercent)
		if err != nil {
			return fmt.Errorf("error reading 'memory_percent': %w", err)
		}
		delete(object, "memory_percent")
	}

	if raw, found := object["port"]; found {
		err = json.Unmarshal(raw, &a.Port)
		if err != nil {
			return fmt.Errorf("error reading 'port': %w", err)
		}
		delete(object, "port")
	}

	if raw, found := object["supported_addons"]; found {
		err = json.Unmarshal(raw, &a.SupportedAddons)
		if err != nil {
			return fmt.Errorf("error reading 'supported_addons': %w", err)
		}
		delete(object, "supported_addons")
	}

	if raw, found := object["vcpus"]; found {
		err = json.Unmarshal(raw, &a.Vcpus)
		if err != nil {
			return fmt.Errorf("error reading 'vcpus': %w", err)
		}
		delete(object, "vcpus")
	}

	if raw, found := object["vgpus"]; found {
		err = json.Unmarshal(raw, &a.Vgpus)
		if err != nil {
			return fmt.Errorf("error reading 'vgpus': %w", err)
		}
		delete(object, "vgpus")
	}

	if raw, found := object["virtualization"]; found {
		err = json.Unmarshal(raw, &a.Virtualization)
		if err != nil {
			return fmt.Errorf("error reading 'virtualization': %w", err)
		}
		delete(object, "virtualization")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Resource to handle AdditionalProperties
func (a Resource) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ID != nil {
		object["_id"], err = json.Marshal(a.ID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '_id': %w", err)
		}
	}

	if a.Active != nil {
		object["active"], err = json.Marshal(a.Active)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'active': %w", err)
		}
	}

	if a.ActiveNodes != nil {
		object["active_nodes"], err = json.Marshal(a.ActiveNodes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'active_nodes': %w", err)
		}
	}

	if a.AggregationPerArchitecture != nil {
		object["aggregation_per_architecture"], err = json.Marshal(a.AggregationPerArchitecture)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'aggregation_per_architecture': %w", err)
		}
	}

	if a.Architecture != nil {
		object["architecture"], err = json.Marshal(a.Architecture)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'architecture': %w", err)
		}
	}

	if a.CandidateLocation != nil {
		object["candidate_location"], err = json.Marshal(a.CandidateLocation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'candidate_location': %w", err)
		}
	}

	if a.CandidateName != nil {
		object["candidate_name"], err = json.Marshal(a.CandidateName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'candidate_name': %w", err)
		}
	}

	if a.CpuHistory != nil {
		object["cpu_history"], err = json.Marshal(a.CpuHistory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cpu_history': %w", err)
		}
	}

	if a.CpuPercent != nil {
		object["cpu_percent"], err = json.Marshal(a.CpuPercent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cpu_percent': %w", err)
		}
	}

	if a.CsiDrivers != nil {
		object["csi_drivers"], err = json.Marshal(a.CsiDrivers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'csi_drivers': %w", err)
		}
	}

	if a.GpuPercent != nil {
		object["gpu_percent"], err = json.Marshal(a.GpuPercent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gpu_percent': %w", err)
		}
	}

	if a.Ip != nil {
		object["ip"], err = json.Marshal(a.Ip)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ip': %w", err)
		}
	}

	if a.LastModifiedTimestamp != nil {
		object["last_modified_timestamp"], err = json.Marshal(a.LastModifiedTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_modified_timestamp': %w", err)
		}
	}

	if a.Memory != nil {
		object["memory"], err = json.Marshal(a.Memory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory': %w", err)
		}
	}

	if a.MemoryHistory != nil {
		object["memory_history"], err = json.Marshal(a.MemoryHistory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory_history': %w", err)
		}
	}

	if a.MemoryPercent != nil {
		object["memory_percent"], err = json.Marshal(a.MemoryPercent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory_percent': %w", err)
		}
	}

	if a.Port != nil {
		object["port"], err = json.Marshal(a.Port)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'port': %w", err)
		}
	}

	if a.SupportedAddons != nil {
		object["supported_addons"], err = json.Marshal(a.SupportedAddons)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'supported_addons': %w", err)
		}
	}

	if a.Vcpus != nil {
		object["vcpus"], err = json.Marshal(a.Vcpus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vcpus': %w", err)
		}
	}

	if a.Vgpus != nil {
		object["vgpus"], err = json.Marshal(a.Vgpus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vgpus': %w", err)
		}
	}

	if a.Virtualization != nil {
		object["virtualization"], err = json.Marshal(a.Virtualization)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'virtualization': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health Liveness probe
	// (GET /)
	Health(c *gin.Context)
	// ListApplications List applications
	// (GET /api/v1/applications)
	ListApplications(c *gin.Context, params ListApplicationsParams)
	// CreateApplication Create an application
	// (POST /api/v1/applications)
	CreateApplication(c *gin.Context)
	// DeleteApplication Delete an application
	// (DELETE /api/v1/applications/{id})
	DeleteApplication(c *gin.Context, id ObjectID)
	// GetApplication Fetch one application
	// (GET /api/v1/applications/{id})
	GetApplication(c *gin.Context, id ObjectID, params GetApplicationParams)
	// PatchApplication Update an application
	// (PATCH /api/v1/applications/{id})
	PatchApplication(c *gin.Context, id ObjectID)
	// ListCustomResourceDefinitions List registered custom resource types
	// (GET /api/v1/custom-resources)
	ListCustomResourceDefinitions(c *gin.Context)
	// CreateCustomResourceDefinition Register a custom resource type
	// (POST /api/v1/custom-resources)
	CreateCustomResourceDefinition(c *gin.Context)
	// DeleteCustomResourceDefinition Delete a custom resource type and every instance of it
	// (DELETE /api/v1/custom-resources/{resource})
	DeleteCustomResourceDefinition(c *gin.Context, resource CustomResourceType)
	// ListCustomResourceInstances List instances of a custom resource type
	// (GET /api/v1/custom-resources/{resource})
	ListCustomResourceInstances(c *gin.Context, resource CustomResourceType)
	// CreateCustomResourceInstance Create an instance of a custom resource type
	// (POST /api/v1/custom-resources/{resource})
	CreateCustomResourceInstance(c *gin.Context, resource CustomResourceType)
	// DeleteCustomResourceInstance Delete a custom resource instance
	// (DELETE /api/v1/custom-resources/{resource}/{id})
	DeleteCustomResourceInstance(c *gin.Context, resource CustomResourceType, id ObjectID)
	// GetCustomResourceInstance Fetch one custom resource instance
	// (GET /api/v1/custom-resources/{resource}/{id})
	GetCustomResourceInstance(c *gin.Context, resource CustomResourceType, id ObjectID)
	// PatchCustomResourceInstance Update a custom resource instance
	// (PATCH /api/v1/custom-resources/{resource}/{id})
	PatchCustomResourceInstance(c *gin.Context, resource CustomResourceType, id ObjectID)
	// ListHooks List webhook registrations
	// (GET /api/v1/hooks)
	ListHooks(c *gin.Context)
	// CreateHook Register a webhook
	// (POST /api/v1/hooks)
	CreateHook(c *gin.Context)
	// DeleteHook Delete a webhook registration
	// (DELETE /api/v1/hooks/{id})
	DeleteHook(c *gin.Context, id ObjectID)
	// GetHook Fetch one webhook registration
	// (GET /api/v1/hooks/{id})
	GetHook(c *gin.Context, id ObjectID)
	// PatchHook Update a webhook registration
	// (PATCH /api/v1/hooks/{id})
	PatchHook(c *gin.Context, id ObjectID)
	// ListJobs List jobs
	// (GET /api/v1/jobs)
	ListJobs(c *gin.Context, params ListJobsParams)
	// CreateJob Create a job
	// (POST /api/v1/jobs)
	CreateJob(c *gin.Context)
	// UpsertJob Create or update a job by name
	// (PUT /api/v1/jobs)
	UpsertJob(c *gin.Context)
	// DeleteJob Delete a job
	// (DELETE /api/v1/jobs/{job_id})
	DeleteJob(c *gin.Context, jobId JobID)
	// GetJob Fetch one job
	// (GET /api/v1/jobs/{job_id})
	GetJob(c *gin.Context, jobId JobID, params GetJobParams)
	// PatchJob Update a job
	// (PATCH /api/v1/jobs/{job_id})
	PatchJob(c *gin.Context, jobId JobID)
	// DeleteJobInstance Delete a job instance
	// (DELETE /api/v1/jobs/{job_id}/{instance_id})
	DeleteJobInstance(c *gin.Context, jobId JobID, instanceId InstanceID)
	// GetJobInstance Fetch one job instance
	// (GET /api/v1/jobs/{job_id}/{instance_id})
	GetJobInstance(c *gin.Context, jobId JobID, instanceId InstanceID)
	// PatchJobInstance Update a job instance
	// (PATCH /api/v1/jobs/{job_id}/{instance_id})
	PatchJobInstance(c *gin.Context, jobId JobID, instanceId InstanceID)
	// AppendJobInstance Append a job instance
	// (PUT /api/v1/jobs/{job_id}/{instance_id})
	AppendJobInstance(c *gin.Context, jobId JobID, instanceId InstanceID)
	// ListResources List candidate resources
	// (GET /api/v1/resources)
	ListResources(c *gin.Context, params ListResourcesParams)
	// CreateResource Create a candidate resource
	// (POST /api/v1/resources)
	CreateResource(c *gin.Context)
	// UpsertResource Create or update a candidate resource by name
	// (PUT /api/v1/resources)
	UpsertResource(c *gin.Context)
	// DeleteResource Delete a candidate resource
	// (DELETE /api/v1/resources/{id})
	DeleteResource(c *gin.Context, id ObjectID)
	// GetResource Fetch one candidate resource
	// (GET /api/v1/resources/{id})
	GetResource(c *gin.Context, id ObjectID)
	// PatchResource Report resource usage for a candidate
	// (PATCH /api/v1/resources/{id})
	PatchResource(c *gin.Context, id ObjectID)
	// GetSpecJSON This OpenAPI document, as JSON
	// (GET /docs/openapi.json)
	GetSpecJSON(c *gin.Context)
	// GetSpecYAML This OpenAPI document, in its source YAML form
	// (GET /docs/openapi.yaml)
	GetSpecYAML(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListApplicationsParams

	// ------------- Optional query parameter "application_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "application_name", c.Request.URL.Query(), &params.ApplicationName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "application_namespace" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "application_namespace", c.Request.URL.Query(), &params.ApplicationNamespace, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_namespace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "userId", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, params)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApplication(c)
}

// DeleteApplication operation middleware
func (siw *ServerInterfaceWrapper) DeleteApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApplication(c, id)
}

// GetApplication operation middleware
func (siw *ServerInterfaceWrapper) GetApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApplicationParams

	// ------------- Optional query parameter "application_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "application_name", c.Request.URL.Query(), &params.ApplicationName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "application_namespace" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "application_namespace", c.Request.URL.Query(), &params.ApplicationNamespace, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_namespace: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "userId", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplication(c, id, params)
}

// PatchApplication operation middleware
func (siw *ServerInterfaceWrapper) PatchApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchApplication(c, id)
}

// ListCustomResourceDefinitions operation middleware
func (siw *ServerInterfaceWrapper) ListCustomResourceDefinitions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCustomResourceDefinitions(c)
}

// CreateCustomResourceDefinition operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomResourceDefinition(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCustomResourceDefinition(c)
}

// DeleteCustomResourceDefinition operation middleware
func (siw *ServerInterfaceWrapper) DeleteCustomResourceDefinition(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resource" -------------
	var resource CustomResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resource", c.Param("resource"), &resource, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resource: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCustomResourceDefinition(c, resource)
}

// ListCustomResourceInstances operation middleware
func (siw *ServerInterfaceWrapper) ListCustomResourceInstances(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resource" -------------
	var resource CustomResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resource", c.Param("resource"), &resource, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resource: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCustomResourceInstances(c, resource)
}

// CreateCustomResourceInstance operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomResourceInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resource" -------------
	var resource CustomResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resource", c.Param("resource"), &resource, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resource: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCustomResourceInstance(c, resource)
}

// DeleteCustomResourceInstance operation middleware
func (siw *ServerInterfaceWrapper) DeleteCustomResourceInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resource" -------------
	var resource CustomResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resource", c.Param("resource"), &resource, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resource: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCustomResourceInstance(c, resource, id)
}

// GetCustomResourceInstance operation middleware
func (siw *ServerInterfaceWrapper) GetCustomResourceInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resource" -------------
	var resource CustomResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resource", c.Param("resource"), &resource, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resource: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCustomResourceInstance(c, resource, id)
}

// PatchCustomResourceInstance operation middleware
func (siw *ServerInterfaceWrapper) PatchCustomResourceInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resource" -------------
	var resource CustomResourceType

	err = runtime.BindStyledParameterWithOptions("simple", "resource", c.Param("resource"), &resource, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resource: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchCustomResourceInstance(c, resource, id)
}

// ListHooks operation middleware
func (siw *ServerInterfaceWrapper) ListHooks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListHooks(c)
}

// CreateHook operation middleware
func (siw *ServerInterfaceWrapper) CreateHook(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateHook(c)
}

// DeleteHook operation middleware
func (siw *ServerInterfaceWrapper) DeleteHook(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteHook(c, id)
}

// GetHook operation middleware
func (siw *ServerInterfaceWrapper) GetHook(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHook(c, id)
}

// PatchHook operation middleware
func (siw *ServerInterfaceWrapper) PatchHook(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchHook(c, id)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobsParams

	// ------------- Optional query parameter "applicationID" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "applicationID", c.Request.URL.Query(), &params.ApplicationID, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter applicationID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "job_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "job_name", c.Request.URL.Query(), &params.JobName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListJobs(c, params)
}

// CreateJob operation middleware
func (siw *ServerInterfaceWrapper) CreateJob(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateJob(c)
}

// UpsertJob operation middleware
func (siw *ServerInterfaceWrapper) UpsertJob(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertJob(c)
}

// DeleteJob operation middleware
func (siw *ServerInterfaceWrapper) DeleteJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteJob(c, jobId)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJobParams

	// ------------- Optional query parameter "instance_number" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "instance_number", c.Request.URL.Query(), &params.InstanceNumber, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_number: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJob(c, jobId, params)
}

// PatchJob operation middleware
func (siw *ServerInterfaceWrapper) PatchJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchJob(c, jobId)
}

// DeleteJobInstance operation middleware
func (siw *ServerInterfaceWrapper) DeleteJobInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "instance_id" -------------
	var instanceId InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "instance_id", c.Param("instance_id"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteJobInstance(c, jobId, instanceId)
}

// GetJobInstance operation middleware
func (siw *ServerInterfaceWrapper) GetJobInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "instance_id" -------------
	var instanceId InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "instance_id", c.Param("instance_id"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJobInstance(c, jobId, instanceId)
}

// PatchJobInstance operation middleware
func (siw *ServerInterfaceWrapper) PatchJobInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "instance_id" -------------
	var instanceId InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "instance_id", c.Param("instance_id"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchJobInstance(c, jobId, instanceId)
}

// AppendJobInstance operation middleware
func (siw *ServerInterfaceWrapper) AppendJobInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "instance_id" -------------
	var instanceId InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "instance_id", c.Param("instance_id"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AppendJobInstance(c, jobId, instanceId)
}

// ListResources operation middleware
func (siw *ServerInterfaceWrapper) ListResources(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListResourcesParams

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", c.Request.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter active: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "job_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "job_id", c.Request.URL.Query(), &params.JobId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "candidate_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "candidate_name", c.Request.URL.Query(), &params.CandidateName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter candidate_name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ip" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ip", c.Request.URL.Query(), &params.Ip, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ip: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "resources" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "resources", c.Request.URL.Query(), &params.Resources, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resources: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListResources(c, params)
}

// CreateResource operation middleware
func (siw *ServerInterfaceWrapper) CreateResource(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateResource(c)
}

// UpsertResource operation middleware
func (siw *ServerInterfaceWrapper) UpsertResource(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertResource(c)
}

// DeleteResource operation middleware
func (siw *ServerInterfaceWrapper) DeleteResource(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteResource(c, id)
}

// GetResource operation middleware
func (siw *ServerInterfaceWrapper) GetResource(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetResource(c, id)
}

// PatchResource operation middleware
func (siw *ServerInterfaceWrapper) PatchResource(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ObjectID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchResource(c, id)
}

// GetSpecJSON operation middleware
func (siw *ServerInterfaceWrapper) GetSpecJSON(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSpecJSON(c)
}

// GetSpecYAML operation middleware
func (siw *ServerInterfaceWrapper) GetSpecYAML(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSpecYAML(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/", wrapper.Health)
	router.GET(options.BaseURL+"/docs/openapi.json", wrapper.GetSpecJSON)
	router.GET(options.BaseURL+"/docs/openapi.yaml", wrapper.GetSpecYAML)
	router.GET(options.BaseURL+"/api/v1/resources", wrapper.ListResources)
	router.POST(options.BaseURL+"/api/v1/resources", wrapper.CreateResource)
	router.PUT(options.BaseURL+"/api/v1/resources", wrapper.UpsertResource)
	router.DELETE(options.BaseURL+"/api/v1/resources/:id", wrapper.DeleteResource)
	router.GET(options.BaseURL+"/api/v1/resources/:id", wrapper.GetResource)
	router.PATCH(options.BaseURL+"/api/v1/resources/:id", wrapper.PatchResource)
	router.GET(options.BaseURL+"/api/v1/applications", wrapper.ListApplications)
	router.POST(options.BaseURL+"/api/v1/applications", wrapper.CreateApplication)
	router.DELETE(options.BaseURL+"/api/v1/applications/:id", wrapper.DeleteApplication)
	router.GET(options.BaseURL+"/api/v1/applications/:id", wrapper.GetApplication)
	router.PATCH(options.BaseURL+"/api/v1/applications/:id", wrapper.PatchApplication)
	router.GET(options.BaseURL+"/api/v1/jobs", wrapper.ListJobs)
	router.POST(options.BaseURL+"/api/v1/jobs", wrapper.CreateJob)
	router.PUT(options.BaseURL+"/api/v1/jobs", wrapper.UpsertJob)
	router.DELETE(options.BaseURL+"/api/v1/jobs/:job_id", wrapper.DeleteJob)
	router.GET(options.BaseURL+"/api/v1/jobs/:job_id", wrapper.GetJob)
	router.PATCH(options.BaseURL+"/api/v1/jobs/:job_id", wrapper.PatchJob)
	router.DELETE(options.BaseURL+"/api/v1/jobs/:job_id/:instance_id", wrapper.DeleteJobInstance)
	router.GET(options.BaseURL+"/api/v1/jobs/:job_id/:instance_id", wrapper.GetJobInstance)
	router.PATCH(options.BaseURL+"/api/v1/jobs/:job_id/:instance_id", wrapper.PatchJobInstance)
	router.PUT(options.BaseURL+"/api/v1/jobs/:job_id/:instance_id", wrapper.AppendJobInstance)
	router.GET(options.BaseURL+"/api/v1/hooks", wrapper.ListHooks)
	router.POST(options.BaseURL+"/api/v1/hooks", wrapper.CreateHook)
	router.DELETE(options.BaseURL+"/api/v1/hooks/:id", wrapper.DeleteHook)
	router.GET(options.BaseURL+"/api/v1/hooks/:id", wrapper.GetHook)
	router.PATCH(options.BaseURL+"/api/v1/hooks/:id", wrapper.PatchHook)
	router.GET(options.BaseURL+"/api/v1/custom-resources", wrapper.ListCustomResourceDefinitions)
	router.POST(options.BaseURL+"/api/v1/custom-resources", wrapper.CreateCustomResourceDefinition)
	router.DELETE(options.BaseURL+"/api/v1/custom-resources/:resource", wrapper.DeleteCustomResourceDefinition)
	router.GET(options.BaseURL+"/api/v1/custom-resources/:resource", wrapper.ListCustomResourceInstances)
	router.POST(options.BaseURL+"/api/v1/custom-resources/:resource", wrapper.CreateCustomResourceInstance)
	router.DELETE(options.BaseURL+"/api/v1/custom-resources/:resource/:id", wrapper.DeleteCustomResourceInstance)
	router.GET(options.BaseURL+"/api/v1/custom-resources/:resource/:id", wrapper.GetCustomResourceInstance)
	router.PATCH(options.BaseURL+"/api/v1/custom-resources/:resource/:id", wrapper.PatchCustomResourceInstance)
}
