apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: Loki
    url: http://loki:3100
    version: 2
    editable: true
    isDefault: true
    jsonData:
      derivedFields:
        - name: "Open matching Oakestra logs"
          matcherRegex: '\b([a-fA-F0-9]{24})\b'
          url: '/d/oakestra-logs/oakestra-orchestrator-logs$${__url_time_range}&var-cluster_id=All&var-compose_service=All&var-search=$${__value.raw}'
          urlDisplayLabel: "Open matching Oakestra logs"
        - name: "Open in Root Scheduler"
          matcherRegex: '\b([a-fA-F0-9]{24})\b'
          url: '/d/oakestra-logs/oakestra-orchestrator-logs$${__url_time_range}&var-cluster_id=root&var-compose_service=root_scheduler&var-search=$${__value.raw}'
          urlDisplayLabel: "Open in Root Scheduler"
        - name: "Open in Cluster Scheduler"
          matcherRegex: '\b([a-fA-F0-9]{24})\b'
          url: '/d/oakestra-logs/oakestra-orchestrator-logs$${__url_time_range}&var-cluster_id=All&var-compose_service=cluster_scheduler&var-search=$${__value.raw}'
          urlDisplayLabel: "Open in Cluster Scheduler"
        - name: "Open in Cluster Manager"
          matcherRegex: '\b([a-fA-F0-9]{24})\b'
          url: '/d/oakestra-logs/oakestra-orchestrator-logs$${__url_time_range}&var-cluster_id=All&var-compose_service=cluster_manager&var-search=$${__value.raw}'
          urlDisplayLabel: "Open in Cluster Manager"
