#!/usr/bin/env python3
"""Generate the Python resource-abstractor client's transport layer.

Regenerates libraries/resource_abstractor_client/resource_abstractor_client/openapi/
from go_resource_abstractor/openapi/openapi.yaml - the same spec the Go server and
its Go client (go_resource_abstractor/client/) are generated from. See
libraries/resource_abstractor_client/README.md for how the generated package is
used: as transport only (request construction), never for parsing responses, since
the abstractor is a schemaless Mongo pass-through that returns documents the spec
doesn't fully describe.

The generator version is pinned here and must stay in step with the pin in
.pre-commit-config.yaml - both read the same spec, and letting them drift would mean
the committed output was generated by a different version of the tool than the one
that checks it in CI.
"""

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

SPEC = REPO_ROOT / "go_resource_abstractor" / "openapi" / "openapi.yaml"
CLIENT_ROOT = REPO_ROOT / "libraries" / "resource_abstractor_client"
CONFIG = CLIENT_ROOT / "openapi" / "config.yaml"
OUTPUT = CLIENT_ROOT / "resource_abstractor_client" / "openapi"

# The generator version comes from whatever's installed (pip install
# openapi-python-client==<pin>), not a flag here - keep the pin in
# .pre-commit-config.yaml's additional_dependencies for the
# generate-python-resource-abstractor-client hook in step with the one below.
# Pinned generator version: 0.29.0


def generate() -> None:
    print(f"Generating Python resource abstractor client from {SPEC.relative_to(REPO_ROOT)}")
    subprocess.run(
        [
            sys.executable,
            "-m",
            "openapi_python_client",
            "generate",
            "--path",
            str(SPEC),
            "--config",
            str(CONFIG),
            "--meta",
            "none",
            "--output-path",
            str(OUTPUT),
            "--overwrite",
        ],
        check=True,
        cwd=REPO_ROOT,
    )


if __name__ == "__main__":
    generate()
