x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:

  # System Manager REST API of Root Orchestrator
  system_manager:
    image: system_manager
    build: system-manager-python/
    hostname: system_manager
    container_name: system_manager
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    expose:
      - "${SYSTEM_MANAGER_PORT}"
      - "50052"
    ports:
      - "${SYSTEM_MANAGER_PORT}:${SYSTEM_MANAGER_PORT}"
      - "50052:50052"
    depends_on:
      - mongo_root
      - cloud_scheduler
      - resource_abstractor
      - root_service_manager
    environment:
      - MY_PORT=${SYSTEM_MANAGER_PORT}
      - CLOUD_MONGO_URL=mongo
      - CLOUD_MONGO_PORT=${CLOUD_MONGO_PORT}
      - CLOUD_SCHEDULER_URL=cloud_scheduler
      - CLOUD_SCHEDULER_PORT=${CLOUD_SCHEDULER_PORT}
      - RESOURCE_ABSTRACTOR_URL=resource_abstractor
      - RESOURCE_ABSTRACTOR_PORT=${RESOURCE_ABSTRACTOR_PORT}
      - NET_PLUGIN_URL=root_service_manager
      - NET_PLUGIN_PORT=${NET_PLUGIN_PORT}
      - JWT_GENERATOR_URL=jwt_generator
      - JWT_GENERATOR_PORT=10011
    logging: *default-logging

  # MongoDB in Root Orchestrator
  mongo_root:
    image: mongo:8.0
    container_name: mongo
    hostname: mongo
    ports:
      - "${CLOUD_MONGO_PORT}:${CLOUD_MONGO_PORT}"
    expose:
      - "${CLOUD_MONGO_PORT}"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port ${CLOUD_MONGO_PORT}

  # cluster-level mongoDB
  mongo_rootnet:
    image: mongo:8.0
    container_name: mongo_net
    hostname: mongo_net
    ports:
      - "${CLOUD_NET_MONGO_PORT}:${CLOUD_NET_MONGO_PORT}"
    volumes:
      - 'mongodb_net_data:/mongodb'
    command: mongod --port ${CLOUD_NET_MONGO_PORT}

  # Cluster Manager
  root_service_manager:
    image: ghcr.io/oakestra/oakestra-net/root-service-manager:latest
    container_name: root_service_manager
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    hostname: root_service_manager
    expose:
      - "${NET_PLUGIN_PORT}"
    ports:
      - "${NET_PLUGIN_PORT}:${NET_PLUGIN_PORT}"
    environment:
      - MY_PORT=${NET_PLUGIN_PORT}
      - SYSTEM_MANAGER_URL=system_manager
      - SYSTEM_MANAGER_PORT=${SYSTEM_MANAGER_PORT}
      - CLOUD_MONGO_URL=mongo_net
      - CLOUD_MONGO_PORT=${CLOUD_NET_MONGO_PORT}
    depends_on:
      - mongo_rootnet

  # Redis for the Cloud Scheduler
  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  # Observability Stack
  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./config/dashboards:/var/lib/grafana/dashboards
    logging: *default-logging

  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    volumes:
      - ./config/loki.yml:/etc/loki/config.yml
      - ./config/alerts/rules.yml:/etc/loki/rules/fake/rules.yml

    command: -config.file=/etc/loki/config.yml
    #logging:
    #  driver: none

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./config/promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--config.file=/etc/promtail/config.yml'
      - '--server.enable-runtime-reload'
    depends_on:
      - loki
    logging: *default-logging

  dashboard:
    image: ghcr.io/oakestra/dashboard:latest
    ports:
      - '80:80'
    restart: unless-stopped
    container_name: oaekstra-frontend-container
    environment:
      - API_ADDRESS=${SYSTEM_MANAGER_URL}:10000

  # Cloud Scheduler
  cloud_scheduler:
    image: cloud_scheduler
    build: cloud-scheduler/
    container_name: cloud_scheduler
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    hostname: cloud_scheduler
    expose:
      - "${CLOUD_SCHEDULER_PORT}"
    ports:
      - "${CLOUD_SCHEDULER_PORT}:${CLOUD_SCHEDULER_PORT}"
    environment:
      - MY_PORT=${CLOUD_SCHEDULER_PORT}
      - SYSTEM_MANAGER_URL=system_manager
      - SYSTEM_MANAGER_PORT=${SYSTEM_MANAGER_PORT}
      - RESOURCE_ABSTRACTOR_URL=resource_abstractor
      - RESOURCE_ABSTRACTOR_PORT=${RESOURCE_ABSTRACTOR_PORT}
      - REDIS_ADDR=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}
    depends_on:
      - redis
      - resource_abstractor
    logging: *default-logging

  resource_abstractor:
    image: resource_abstractor
    build: resource-abstractor/
    container_name: resource_abstractor
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    hostname: resource_abstractor
    expose:
      - "${RESOURCE_ABSTRACTOR_PORT}"
    ports:
      - "${RESOURCE_ABSTRACTOR_PORT}:${RESOURCE_ABSTRACTOR_PORT}"
    environment:
      - RESOURCE_ABSTRACTOR_PORT=${RESOURCE_ABSTRACTOR_PORT}
      - CLOUD_MONGO_URL=mongo
      - CLOUD_MONGO_PORT=${CLOUD_MONGO_PORT}
    depends_on:
      - mongo_root
    logging: *default-logging

volumes:
  mongodb_data:
    driver: local
  mongodb_net_data:
    driver: local
