services:
  system_manager:
    image: ghcr.io/oakestra/oakestra/root-system-manager:latest
    pull_policy: always

  mongo_root:
    image: mongo:8.0
    pull_policy: always

  mongo_rootnet:
    image: mongo:8.0
    pull_policy: always

  root_service_manager:
    image: ghcr.io/oakestra/oakestra-net/root-service-manager:latest
    pull_policy: always

  root_redis:
    image: redis
    pull_policy: always

  grafana:
    image: grafana/grafana
    pull_policy: always

  loki:
    image: grafana/loki:2.9.2
    pull_policy: always

  promtail:
    image: grafana/promtail:2.9.2
    pull_policy: always
    
  root_scheduler:
    image: ghcr.io/oakestra/oakestra/scheduler:latest
    pull_policy: always
    
  root_resource_abstractor:
    image: ghcr.io/oakestra/oakestra/resource-abstractor:latest
    pull_policy: always

  addons_manager:
    image: ghcr.io/oakestra/oakestra/addons_manager:latest
    pull_policy: always

  addons_monitor:
    image: ghcr.io/oakestra/oakestra/addons_monitor:latest
    pull_policy: always

  marketplace_manager:
    image: ghcr.io/oakestra/oakestra/marketplace_manager:latest
    pull_policy: always

  addons_dashboard:
    image: ghcr.io/oakestra/oakestra/addons_dashboard:latest
    pull_policy: always

  jwt_generator:
    image: ghcr.io/oakestra/oakestra/jwt-generator:latest
    pull_policy: always
    
