// Package openapi is the generated client half of the resource abstractor's
// API contract.
//
// The contract itself lives one directory up and one module over, in
// go_resource_abstractor/openapi/openapi.yaml - a single spec from which both
// directions are generated: the gin server the service implements, and the
// ClientWithResponses below that callers use to reach it. An endpoint that
// isn't in the spec therefore exists on neither side.
//
// Most callers want the ergonomic facade in the parent package (client)
// rather than this one, which has a method per operationId and no
// not-found/error mapping. Reach for this package directly for the endpoints
// the facade doesn't wrap - /hooks and /custom-resources.
//
// The one part of the spec with no client method is the Docs tag, excluded in
// cfg.yaml: those endpoints serve this very document, which anything linking
// this package already has.
//
// Regenerate with `go generate ./openapi` from the client module root, after
// editing the spec. The generator version pinned below must stay in step with
// the one in go_resource_abstractor/openapi/spec.go: the two read the same
// file, and letting them drift would mean the server and the client were
// generated by different versions of the same tool.
package openapi

//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0 -config cfg.yaml ../../openapi/openapi.yaml
