name: Docker addons-engine-images

on:
  push:
    tags:
      - 'v*.*.*'
      - 'alpha-v*.*.*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-addons-manager:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: addons_manager
      context: ./addons_engine/addons-manager/
      build_args: |
        LIB_BRANCH=${{ github.head_ref || github.ref_name }}
    secrets: inherit

  build-addons-monitor:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: addons_monitor
      context: ./addons_engine/addons-monitor/
      build_args: |
        LIB_BRANCH=${{ github.head_ref || github.ref_name }}
    secrets: inherit

  build-marketplace-manager:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: marketplace_manager
      context: ./addons_marketplace/marketplace-manager/
      build_args: |
        LIB_BRANCH=${{ github.head_ref || github.ref_name }}
    secrets: inherit

  build-addons-dashboard:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: addons_dashboard
      context: ./addons_engine/addons-dashboard/
      # dashboard does not support armhf and has no Python lib dependency
      platforms: linux/amd64,linux/arm64
    secrets: inherit
