name: Create release tags

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_tag:
    uses: oakestra/.github/.github/workflows/create-tag.yml@main
    with:
      force: true
    secrets: inherit
