name: Create alpha tags

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  create_tag:
    uses: oakestra/.github/.github/workflows/create-tag.yml@main
    with:
      tag_prefix: 'alpha-'
      force: true
    secrets: inherit
