name: Docker csi-hostpath-plugin

on:
  push:
    tags:
      - 'v*.*.*'
      - 'alpha-v*.*.*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@v1
    with:
      image_name: csi-hostpath-plugin
      context: ./csi/hostpath/
    secrets: inherit
