name: Docker jwt-generator-image

on:
  push:
    tags:
      - 'v*.*.*'
      - 'alpha-v*.*.*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: jwt-generator
      context: ./root_orchestrator/jwt-generator/
    secrets: inherit
