name: AI Fix Dispatcher
on:
  issues:
    types: [assigned]
  pull_request:
    types: [assigned,review_requested]
  issue_comment:
    types: [created]

jobs:
  call:
    uses: oakestra/.github/.github/workflows/oakassistant.yml@main
    secrets: inherit
    with:
      bot_username: OakAssistant
      environment_name: OakAssistant
