name: Testbed Oneshot - Intermediate Approval Check

# This action validates the PR approval before initiating the testbed deployment.
# It triggers the deployment through the `oneshot_testbed_workflow_run` action.
# By decoupling the deployment process from the waiting cycle, this setup allows external forks to execute 
# without passing any sensitive secrets or execution rights to the forked repository.
# The `oneshot_testbed_workflow_run` action handles the testbed deployment and reports the outcome (success or failure).


on:
    pull_request_review:
      types: [submitted]

jobs:
  check:
    name: Waiting Termination of Testbed Oneshot Execution Workflow
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
        - name: Testbed Oneshot Execution - Waiting cycle
          uses: lewagon/wait-on-check-action@v1.3.4
          with:
              ref: ${{ github.ref }}
              check-name: 'Trigger Testbed Oneshot Execution'
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              wait-interval: 20
              allowed-conclusions: success
