name: Docker resource-abstractor-image

on:
  push:
    tags:
      - 'v*.*.*'
      - 'alpha-v*.*.*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@v1
    with:
      image_name: resource-abstractor
      context: ./resource-abstractor/
    secrets: inherit
