name: Docker root-system-manager-python

on:
  push:
    tags:
      - 'v*.*.*'
      - 'alpha-v*.*.*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: oakestra/.github/.github/workflows/docker-build-push.yml@v1
    with:
      image_name: root-system-manager
      context: ./root_orchestrator/system-manager-python/
      build_args: |
        LIB_BRANCH=${{ github.head_ref || github.ref_name }}
    secrets: inherit
